package com.sicompany.godoc.screens;

import com.sicompany.godoc.accounts.Admin;
import com.sicompany.godoc.accounts.Pasien;
import com.sicompany.godoc.accounts.Roles;
import com.sicompany.godoc.accounts.User;
import com.sicompany.godoc.connections.DbConnection;
import javax.swing.JOptionPane;

/**
 * 
 * @author Kelompok 2
 */
public class RegisterScreen extends javax.swing.JFrame {

    /**
     * 
     */
    public RegisterScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenisKelaminGroup = new javax.swing.ButtonGroup();
        titleLabel = new javax.swing.JLabel();
        namaLengkapLabel = new javax.swing.JLabel();
        namaLengkapField = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        verifyPasswordLabel = new javax.swing.JLabel();
        verifyPasswordField = new javax.swing.JPasswordField();
        noTelpLabel = new javax.swing.JLabel();
        roleLabel = new javax.swing.JLabel();
        roleDropdown = new javax.swing.JComboBox<>();
        jenisKelaminLabel = new javax.swing.JLabel();
        lakiLakiRadioButton = new javax.swing.JRadioButton();
        perempuanRadioButton = new javax.swing.JRadioButton();
        alamatLabel = new javax.swing.JLabel();
        alamatScrollPane = new javax.swing.JScrollPane();
        alamatTextArea = new javax.swing.JTextArea();
        gotoLoginButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        noTelpField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GoDoc - Pendaftaran Akun");

        titleLabel.setFont(new java.awt.Font("Ubuntu Thin", 1, 24)); // NOI18N
        titleLabel.setText("GoDoc");

        namaLengkapLabel.setText("Nama Lengkap");

        namaLengkapField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaLengkapFieldActionPerformed(evt);
            }
        });

        usernameLabel.setText("Username");

        passwordLabel.setText("Password");

        verifyPasswordLabel.setText("Konfirmasi Password");

        noTelpLabel.setText("Nomor Telepon");

        roleLabel.setText("Role");

        roleDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pasien", "Admin" }));

        jenisKelaminLabel.setText("Jenis Kelamin");

        jenisKelaminGroup.add(lakiLakiRadioButton);
        lakiLakiRadioButton.setText("Laki-laki");
        lakiLakiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiLakiRadioButtonActionPerformed(evt);
            }
        });

        jenisKelaminGroup.add(perempuanRadioButton);
        perempuanRadioButton.setText("Perempuan");
        perempuanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perempuanRadioButtonActionPerformed(evt);
            }
        });

        alamatLabel.setText("Alamat");

        alamatTextArea.setColumns(20);
        alamatTextArea.setRows(5);
        alamatScrollPane.setViewportView(alamatTextArea);

        gotoLoginButton.setText("Sudah Punya Akun");
        gotoLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoLoginButtonActionPerformed(evt);
            }
        });

        registerButton.setText("Daftar Sekarang");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(titleLabel)
                        .addGap(230, 230, 230))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaLengkapLabel)
                            .addComponent(usernameLabel)
                            .addComponent(passwordLabel)
                            .addComponent(verifyPasswordLabel)
                            .addComponent(jenisKelaminLabel)
                            .addComponent(noTelpLabel))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(verifyPasswordField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passwordField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(namaLengkapField)
                            .addComponent(usernameField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lakiLakiRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(perempuanRadioButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(noTelpField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(gotoLoginButton)
                        .addGap(18, 18, 18)
                        .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 126, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roleLabel)
                            .addComponent(alamatLabel))
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alamatScrollPane)
                            .addComponent(roleDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLengkapField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaLengkapLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(perempuanRadioButton)
                    .addComponent(lakiLakiRadioButton)
                    .addComponent(jenisKelaminLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verifyPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verifyPasswordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(noTelpLabel)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(roleLabel)
                            .addComponent(roleDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alamatLabel)
                            .addComponent(alamatScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gotoLoginButton)
                            .addComponent(registerButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(noTelpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaLengkapFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaLengkapFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaLengkapFieldActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        
        String namaLengkap = namaLengkapField.getText();
        String username = usernameField.getText();
        String password = passwordField.getText();
        String verifyPassword = verifyPasswordField.getText();
        String noHp = noTelpField.getText();
        String alamat = alamatTextArea.getText();

        String jenisKelamin = "";
        if (lakiLakiRadioButton.isSelected())
            jenisKelamin = "L";
        else if (perempuanRadioButton.isSelected())
            jenisKelamin = "P";
        
        Roles role = null;
        if("Admin".equals(roleDropdown.getSelectedItem()))
            role = Roles.ADMIN;
        else if("Pasien".equals(roleDropdown.getSelectedItem()))
            role = Roles.PASIEN;
        
        if(namaLengkap.isEmpty() || username.isEmpty() || password.isEmpty() || verifyPassword.isEmpty() || noHp.isEmpty() || alamat.isEmpty() || jenisKelamin.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mohon isi semua data!");
            return;
        }

        else if(!password.equals(verifyPassword)) {
            JOptionPane.showMessageDialog(this, "Password tidak sama!");
            return;
        }

        String userId = DbConnection.generateUserID(role);
        User newUser;
        
        if(role == Roles.ADMIN)
            newUser = new Admin(userId, username, password);
        
        else {
            newUser = new Pasien(userId, username, password);
            ((Pasien) newUser).setNamaLengkap(namaLengkap);
            ((Pasien) newUser).setJenisKelamin(jenisKelamin);
            ((Pasien) newUser).setNoHp(noHp);
            ((Pasien) newUser).setAlamat(alamat);
        }
        
        if(DbConnection.register(newUser.getId(), newUser.getUsername(), newUser.getPassword(), newUser.getRole())) {

            if(role == Roles.PASIEN)
                DbConnection.tambahPasien((Pasien) newUser);

            JOptionPane.showMessageDialog(this, "Registrasi berhasil!");

            this.dispose();
            new MainScreen(newUser).setVisible(true);
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    private void lakiLakiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiLakiRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lakiLakiRadioButtonActionPerformed

    private void perempuanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perempuanRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perempuanRadioButtonActionPerformed


    private void gotoLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoLoginButtonActionPerformed
        
        this.dispose();
        new LoginScreen().setVisible(true);
    }//GEN-LAST:event_gotoLoginButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamatLabel;
    private javax.swing.JScrollPane alamatScrollPane;
    private javax.swing.JTextArea alamatTextArea;
    private javax.swing.JButton gotoLoginButton;
    private javax.swing.ButtonGroup jenisKelaminGroup;
    private javax.swing.JLabel jenisKelaminLabel;
    private javax.swing.JRadioButton lakiLakiRadioButton;
    private javax.swing.JTextField namaLengkapField;
    private javax.swing.JLabel namaLengkapLabel;
    private javax.swing.JTextField noTelpField;
    private javax.swing.JLabel noTelpLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JRadioButton perempuanRadioButton;
    private javax.swing.JButton registerButton;
    private javax.swing.JComboBox<String> roleDropdown;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JPasswordField verifyPasswordField;
    private javax.swing.JLabel verifyPasswordLabel;
    // End of variables declaration//GEN-END:variables
}
